### PR TITLE
Feat/va-file-upload

### LINKED ISSUE #526: File upload restyle
### References
- [ant design](https://vue.ant.design/components/upload/)([source](https://github.com/vueComponent/ant-design-vue/blob/master/components/upload/Upload.jsx))

### PR DESCRIPTION
**Pull request by nastassiadanilova**
close #526 

- [x] restyle
- [x] docs
- [x] demo

### CODE REVIEW

**Comment by Eugenizer** [comment]
@nastassiadanilova 
In general - everything is fine.

Questions / suggestions:
1. No indent under the button on small resolutions - http://piclair.com/data/jnamm.jpg
2. Delete icon looks pressed to the righ in list - http://piclair.com/data/5w9pb.jpg
3. Why do you use a fixed size for items in gallery? It may be better to use flex and make them responsive

**Comment by nastassiadanilova** [comment]
@asvae , can we move defaultFiles feature to the vuestic2.1 and merge this?

**Comment by asvae** [comment]
@nastassiadanilova sure. Let's do that.

I have split to issue: #600

**Comment by asvae** [comment]
@smellyshovel please check/fix if themes operate correctly in this component. Then squash + merge when everything is fine.

**Pull request merged**
