### PR TITLE
chore: swap font. Source Pro -> Inter (#940)

### LINKED ISSUE #940: Change font
There is a font change and we have to replace existing font for vuestic admin with https://fonts.google.com/specimen/Inter. Check so that it looks close to design.

There is no plan to backport it to vuestic-ui for now. Key reason is that it's hard to manage breaking change.

### PR DESCRIPTION
**Pull request by Stars22**
This closes #940

### CODE REVIEW

**Comment by asvae** [comment]
Couple of things I noticed looking at screenshot:
* Can we also change fonts in charts?

* Font went up in size significantly, is that intentional?
  image
  image

**Comment by Stars22** [comment]
> Couple of things I noticed looking at screenshot:
> 
> * Can we also change fonts in charts?
> * Font went up in size significantly, is that intentional?
>   image
>   image

I'm not sure about 'intentional' change of font size, but no changes are made for css font-sizes. Different fonts differ in sizes, so it's probably the case.

**Review by asvae — APPROVED** [review]
🫡

**Comment by asvae** [comment]
Congrats on first PR 🤗

**Pull request merged**
