### PR TITLE
Layout tweaks

### PR DESCRIPTION
**Pull request by VasylHryha**
## Description

close https://github.com/epicmaxco/vuestic-admin/issues/991

</details>

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any feature but make things better)

### CODE REVIEW

**Comment by VasylHryha** [comment]
new preview with fixed styles
image

**Comment by VasylHryha** [comment]
Also, I liked previous breadcrumbs more than current, not sure why it's not ok to display parent route

**Comment by asvae** [comment]
@VasylHryha maybe we should roll them back, I found that design confusing as well

**Review by asvae — APPROVED** [review]
Thanks!

**Pull request merged**
